import AppHeader from '../components/AppHeader';
import './global.css';

export const metadata = {
  title: 'Welcome to dynamic-form',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="valentine">
      <body className="h-screen flex flex-col">
        <header className="shrink-0">
          <AppHeader />
        </header>
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
